name: relieverapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #video_player: ^0.10.4+1
  video_player: ^0.10.12+2
  chewie: ^0.9.8
  video_player_platform_interface: ^2.1.0
  #carousel_slider: ^1.0.1
  #simple_slider: ^0.0.2
  #simple_slider: ^0.0.1
  table_calendar: ^2.2.3
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  firebase_helpers: ^0.1.1
  firebase_database: ^3.1.5
  http: ^0.12.1
  speech_to_text: ^2.4.1
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  syncfusion_flutter_gauges: ^18.1.59
  percent_indicator: ^2.1.1
  pie_chart: ^3.1.1
  google_fonts: ^1.0.0
  youtube_player_flutter: ^7.0.0+7
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: Image/Icon.png
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   #- assets/
  # - assets/
   - assets/LG5.png
   - assets/Asset7.png
   - assets/images/bad1.png
   - assets/normal.png
  # - assets/stress.png
   - assets/images/Happy.png
   - assets/Calm.png
   - assets/Surprised.png
   - assets/Funny.png
   - assets/Sleepy.png
   - assets/happyLevel.png
   - assets/normalLevel.png
   - assets/images/stressLevel.png
   - assets/vstressLevel.png
   - assets/Work.png
   - assets/Society.png
   - assets/Sleep.png
   - assets/Emotional.png
   - assets/Eat.png
   - assets/Nothing.png
   - assets/Unknown.png

fonts: 
  - family: Circular
    fonts: 
      - asset: fonts/CircularStd-Medium.ttf
      - asset: fonts/CircularStd-Bold.ttf
        weight: 500
      - asset: fonts/Circular Air Light.ttf
        weight: 100
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
